Server exception occurred
Traceback (most recent call last):
  File "http.py", line 171, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './favicon.ico'
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 171, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './in.html'
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 171, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './in.html'
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 171, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './in.html'
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 171, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './in.html'
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 171, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './in.html'
Server exception occurred
Traceback (most recent call last):
  File "/home/shaunak/COMPUTER_NETWORK/Project/http.py", line 171, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './favicon.ico'
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 171, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './favicon.ico'
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 277, in client_thread
    responseHeader += create_header(responseHeader, 0, requestedFileType, "put")
UnboundLocalError: local variable 'requestedFileType' referenced before assignment
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 199, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './favicon.ico'
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 199, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './a/img_chania.jpg'
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 199, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './a/1920px-HTTP_logo.svg.png'
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 199, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './a/traceroute.png'
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 199, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './index3.html'
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 199, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './index3.html'
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 200, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './index3.html'
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 200, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './index3.html'
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 200, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './index3.html'
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 200, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './index3.html'
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 204, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './favicon.ico'
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 204, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './index3.html'
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 204, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './index3.html'
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 204, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './favicon.ico'
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 203, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './index4.html'
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 206, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './index4.html'
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 312, in client_thread
    responseHeader += create_header(responseHeader, 0, requestedFileType, "put")
UnboundLocalError: local variable 'requestedFileType' referenced before assignment
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 206, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './a/img_chania.jpg'
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 206, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './a/1920px-HTTP_logo.svg.png'
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 206, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './a/traceroute.png'
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 315, in client_thread
    responseHeader += create_header(responseHeader, 0, requestedFileType, "put")
UnboundLocalError: local variable 'requestedFileType' referenced before assignment
