Server exception occurred
Traceback (most recent call last):
  File "http.py", line 223, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './a/img_chania.jpg'
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 223, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './a/1920px-HTTP_logo.svg.png'
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 223, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './a/traceroute.png'
