Server exception occurred
Traceback (most recent call last):
  File "http.py", line 171, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './favicon.ico'
Server exception occurred
Traceback (most recent call last):
  File "http.py", line 170, in client_thread
    requestedFile = open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './favicon.ico'
